CREATE TABLE books (
  id INT PRIMARY KEY AUTO_INCREMENT,
  author VARCHAR(1000) NOT NULL,
  title VARCHAR(1000) NOT NULL,
  isbn VARCHAR(100) NOT NULL,
  publishYear NUMERIC(4) NOT NULL,
  reserved BOOLEAN NOT NULL DEFAULT FALSE
);

